// AdcState.h was generated by ProtoGen version 2.17.b

#ifndef _ADCSTATE_H
#define _ADCSTATE_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "PpdsMotorPodProtocol.h"

/*!
 * ADC state.
 */
typedef struct
{
    float current;    
    float voltage;    
    float temperature;
}AdcState_t;

//! Encode a AdcState_t structure into a byte array
void encodeAdcState_t(uint8_t* data, int* bytecount, const AdcState_t* user);

//! Decode a AdcState_t structure from a byte array
int decodeAdcState_t(const uint8_t* data, int* bytecount, AdcState_t* user);

//! Create the AdcState packet
void encodeAdcStatePacketStructure(CorvoPacket* pkt, const AdcState_t* user);

//! Decode the AdcState packet
int decodeAdcStatePacketStructure(const CorvoPacket* pkt, AdcState_t* user);

//! return the packet ID for the AdcState packet
#define getAdcStatePacketID() (ADC_STATE)

//! return the minimum encoded length for the AdcState packet
#define getAdcStateMinDataLength() (12)

//! return the maximum encoded length for the AdcState packet
#define getAdcStateMaxDataLength() (12)

#ifdef __cplusplus
}
#endif
#endif
