// HardwareVersion.h was generated by ProtoGen version 2.17.b

#ifndef _HARDWAREVERSION_H
#define _HARDWAREVERSION_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "PpdsMotorPodProtocol.h"

/*!
 * Hardware revision information.
 */
typedef struct
{
    char    id[12];
    uint8_t major; 
    uint8_t minor; 
}HardwareVersion_t;

//! Encode a HardwareVersion_t structure into a byte array
void encodeHardwareVersion_t(uint8_t* data, int* bytecount, const HardwareVersion_t* user);

//! Decode a HardwareVersion_t structure from a byte array
int decodeHardwareVersion_t(const uint8_t* data, int* bytecount, HardwareVersion_t* user);

//! Create the HardwareVersion packet
void encodeHardwareVersionPacketStructure(CorvoPacket* pkt, const HardwareVersion_t* user);

//! Decode the HardwareVersion packet
int decodeHardwareVersionPacketStructure(const CorvoPacket* pkt, HardwareVersion_t* user);

//! return the packet ID for the HardwareVersion packet
#define getHardwareVersionPacketID() (HARDWARE_VERSION)

//! return the minimum encoded length for the HardwareVersion packet
#define getHardwareVersionMinDataLength() (3)

//! return the maximum encoded length for the HardwareVersion packet
#define getHardwareVersionMaxDataLength() (14)

#ifdef __cplusplus
}
#endif
#endif
