// InterfaceVersion.h was generated by ProtoGen version 2.17.b

#ifndef _INTERFACEVERSION_H
#define _INTERFACEVERSION_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "PpdsMotorPodProtocol.h"

/*!
 * Interface version information.
 */
typedef struct
{
    char    id[12];
    uint8_t major; 
    uint8_t minor; 
    uint8_t patch; 
}InterfaceVersion_t;

//! Encode a InterfaceVersion_t structure into a byte array
void encodeInterfaceVersion_t(uint8_t* data, int* bytecount, const InterfaceVersion_t* user);

//! Decode a InterfaceVersion_t structure from a byte array
int decodeInterfaceVersion_t(const uint8_t* data, int* bytecount, InterfaceVersion_t* user);

//! Create the InterfaceVersion packet
void encodeInterfaceVersionPacketStructure(CorvoPacket* pkt, const InterfaceVersion_t* user);

//! Decode the InterfaceVersion packet
int decodeInterfaceVersionPacketStructure(const CorvoPacket* pkt, InterfaceVersion_t* user);

//! return the packet ID for the InterfaceVersion packet
#define getInterfaceVersionPacketID() (INTERFACE_VERSION)

//! return the minimum encoded length for the InterfaceVersion packet
#define getInterfaceVersionMinDataLength() (4)

//! return the maximum encoded length for the InterfaceVersion packet
#define getInterfaceVersionMaxDataLength() (15)

#ifdef __cplusplus
}
#endif
#endif
