// OpticalFlowState.h was generated by ProtoGen version 2.17.b

#ifndef _OPTICALFLOWSTATE_H
#define _OPTICALFLOWSTATE_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 */

#include "PpdsMotorPodProtocol.h"

typedef struct
{
    int16_t x;
    int16_t y;
}flowDelta_t;

/*!
 * Optical Flow state.
 */
typedef struct
{
    uint32_t    timeDelta_us;  
    uint8_t     surfaceQuality; //!< surface quality
    flowDelta_t flowDelta;     
}OpticalFlowState_t;

//! Encode a OpticalFlowState_t structure into a byte array
void encodeOpticalFlowState_t(uint8_t* data, int* bytecount, const OpticalFlowState_t* user);

//! Decode a OpticalFlowState_t structure from a byte array
int decodeOpticalFlowState_t(const uint8_t* data, int* bytecount, OpticalFlowState_t* user);

//! Create the OpticalFlowState packet
void encodeOpticalFlowStatePacketStructure(CorvoPacket* pkt, const OpticalFlowState_t* user);

//! Decode the OpticalFlowState packet
int decodeOpticalFlowStatePacketStructure(const CorvoPacket* pkt, OpticalFlowState_t* user);

//! return the packet ID for the OpticalFlowState packet
#define getOpticalFlowStatePacketID() (OPTICAL_FLOW_STATE)

//! return the minimum encoded length for the OpticalFlowState packet
#define getOpticalFlowStateMinDataLength() (9)

//! return the maximum encoded length for the OpticalFlowState packet
#define getOpticalFlowStateMaxDataLength() (9)

#ifdef __cplusplus
}
#endif
#endif
