// PpdsMotorPodProtocol.h was generated by ProtoGen version 2.17.b

#ifndef _PPDSMOTORPODPROTOCOL_H
#define _PPDSMOTORPODPROTOCOL_H

// C++ compilers: don't mangle us
#ifdef __cplusplus
extern "C" {
#endif

/*!
 * \file
 * \mainpage PpdsMotorPod protocol stack
 *
 * This is the external interface for the PPDS Motor Pod firmware, generated
 * with ProtoGen.
 *
 * The protocol version is 0.0.1.b
 */

#include <stdint.h>
#include "corvo_packet.h"	// Definition for Corvo packet structure.

//! \return the protocol version string
#define getPpdsMotorPodVersion() "0.0.1.b"

/*!
 * The list of packet identifiers.
 */
typedef enum
{
    OPTICAL_FLOW_STATE,//!< The data measured by the Optical Flow sensor.
    ADC_STATE        //!< The data measured by the ADC.
} PacketIds;


// The prototypes below provide an interface to the packets.
// They are not auto-generated functions, but must be hand-written

//! \return the packet data pointer from the packet
uint8_t* getPpdsMotorPodPacketData(CorvoPacket* pkt);

//! \return the packet data pointer from the packet, const
const uint8_t* getPpdsMotorPodPacketDataConst(const CorvoPacket* pkt);

//! Complete a packet after the data have been encoded
void finishPpdsMotorPodPacket(CorvoPacket* pkt, int size, uint32_t packetID);

//! \return the size of a packet from the packet header
int getPpdsMotorPodPacketSize(const CorvoPacket* pkt);

//! \return the ID of a packet from the packet header
uint32_t getPpdsMotorPodPacketID(const CorvoPacket* pkt);

#ifdef __cplusplus
}
#endif
#endif
